/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cody_ndksimpledemo_NDKUtil */

#ifndef _Included_com_cody_ndksimpledemo_NDKUtil
#define _Included_com_cody_ndksimpledemo_NDKUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cody_ndksimpledemo_NDKUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cody_ndksimpledemo_NDKUtil_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
